-- ==========================================================
-- LuxeCraft Watches - Supabase Database Schema & RLS Security
-- Run this in the Supabase Dashboard -> SQL Editor
-- ==========================================================

-- 1. Ensure 'orders' table exists with all required fields
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    customer_email TEXT,
    customer_address TEXT NOT NULL,
    city TEXT NOT NULL,
    items JSONB NOT NULL DEFAULT '[]'::jsonb,
    subtotal NUMERIC(10, 2) NOT NULL DEFAULT 0,
    shipping_fee NUMERIC(10, 2) NOT NULL DEFAULT 0,
    discount NUMERIC(10, 2) NOT NULL DEFAULT 0,
    total NUMERIC(10, 2) NOT NULL DEFAULT 0,
    payment_method TEXT NOT NULL DEFAULT 'Cash on Delivery (COD)',
    status TEXT NOT NULL DEFAULT 'pending',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS) on orders
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- 3. Security Policy: Allow store visitors to place orders (INSERT only)
-- Customers can submit orders during checkout without seeing anyone else's data
DROP POLICY IF EXISTS "Allow public checkout insert" ON public.orders;
CREATE POLICY "Allow public checkout insert"
    ON public.orders
    FOR INSERT
    TO anon, authenticated
    WITH CHECK (true);

-- 4. Security Policy: Only authenticated store admins can view orders (SELECT)
-- Public users and strangers cannot read or list customer orders
DROP POLICY IF EXISTS "Allow admin to select orders" ON public.orders;
CREATE POLICY "Allow admin to select orders"
    ON public.orders
    FOR SELECT
    TO authenticated
    USING (true);

-- 5. Security Policy: Only authenticated store admins can update orders (UPDATE)
-- Admins can update status: pending, confirmed, processing, shipped, delivered, cancelled
DROP POLICY IF EXISTS "Allow admin to update orders" ON public.orders;
CREATE POLICY "Allow admin to update orders"
    ON public.orders
    FOR UPDATE
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- 6. Security Policy: Only authenticated store admins can delete orders (DELETE)
DROP POLICY IF EXISTS "Allow admin to delete orders" ON public.orders;
CREATE POLICY "Allow admin to delete orders"
    ON public.orders
    FOR DELETE
    TO authenticated
    USING (true);

-- 7. Ensure public read access for active products
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public to view active products" ON public.products;
CREATE POLICY "Allow public to view active products"
    ON public.products
    FOR SELECT
    TO anon, authenticated
    USING (true);

DROP POLICY IF EXISTS "Allow admin full access to products" ON public.products;
CREATE POLICY "Allow admin full access to products"
    ON public.products
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- 8. Ensure public read access for site settings
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public to view site_settings" ON public.site_settings;
CREATE POLICY "Allow public to view site_settings"
    ON public.site_settings
    FOR SELECT
    TO anon, authenticated
    USING (true);

DROP POLICY IF EXISTS "Allow admin full access to site_settings" ON public.site_settings;
CREATE POLICY "Allow admin full access to site_settings"
    ON public.site_settings
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);
